### ISSUE TITLE
Feature Request: Backstage Integration 

### ISSUE THREAD

**Issue by regicsolutions** [DataDog/build-plugin#25]
The Backstage community has been talking about a need for a DataDog plugin, this seems like it would be a great start! 

https://github.com/backstage/backstage/issues/849

**Comment by yoannmoinet** [comment]
Hi there :wave:
I'm not sure I see how this is related to the `build-plugin` itself.
It sounds like you're looking for a general purpose plugin that would communicate between Datadog and your service, am I right?

The `build-plugin` is specifically made for build systems like Webpack.

I'll close the issue for now as it sounds unrelated to this specific package.
Feel free to re-open if you think it is in fact very related, giving more information on your need.

Cheers!
