### ISSUE TITLE
[feature request] Default Dashboard JSON Configuration

### ISSUE THREAD

**Issue by hydrosquall** [DataDog/build-plugin#26]
It would be useful to be able to have access to the dashboard JSON required to generate this picture, rather creating the tiles individually for each new org we set this up for

![dash](https://github.com/DataDog/build-plugin/raw/master/assets/datadog-dashboard.png)

 I've just set this plugin up for nycvaccinelist.com, and wanted to check if there's a way we can get this default integration dashboard in a few clicks.

**Comment by hydrosquall** [comment]
Alternately, it might be necessary to programmatically generate this JSON rather than doing a 1-time export, since we may have to add a prefix to keep the metric names organized like `js-build-plugin.`

**Comment by yoannmoinet** [comment]
Unfortunately, we don't have any integration (yet).

I'm not sure I'm following
> programmatically generate this JSON rather than doing a 1-time export

Do you mean that the exported JSON you get isn't enough for what you need?

**Comment by hydrosquall** [comment]
> Do you mean that the exported JSON you get isn't enough for what you need?

Ah, to clarify what I meant was that exporting the JSON from Datadog's usage of this plugin doesn't work out-of-the-box since I have a `prefix` [doc](https://github.com/DataDog/build-plugin/tree/master/src/hooks/datadog#datadogprefix) that ended up being slightly different.

 Additionally, people outside the Datadog org don't have access to our dashboard JSON, so it seems that they would have to build this view up themselves.

**Comment by hydrosquall** [comment]
@yoannmoinet would it be ok for us to open source our build plugin dashboard JSON configuration, even without the "dynamic prefix generation" step I proposed above? This way, @icirellik's team would be able to have our setup as a starting point.

**Comment by leggomuhgreggo** [comment]
Hey @hydrosquall is that dashboard JSON still available? Would very much appreciate!

**Comment by yoannmoinet** [comment]
So sorry for the delays.
I've created #39, let me know if that would work.
I'll merge it once you give me a ✅

**Comment by hydrosquall** [comment]
Hi @icirellik / @leggomuhgreggo / @irudoy thanks for your interest in this feature.  Not sure if you saw https://github.com/DataDog/build-plugin/pull/39, let us know how it goes with applying the default dashboard to your setups :).
