### ISSUE TITLE
Question/Feature request - Control what gets logged to the console when metrics are sent to DataDog

### ISSUE THREAD

**Issue by SalimBensiali** [DataDog/build-plugin#35]
Hi, 

Thanks for this plugin. I was wondering if you would be open to a PR that provides an option to turn off or allow to control the detail of what gets output to the console when sending metric to DataDog. 

The `console.log` lines are https://github.com/DataDog/build-plugin/blob/229d59a712045822cc3a0dbe5637cbb77c801c1d/src/hooks/datadog/sender.ts#L25-L28

Thanks.

**Comment by yoannmoinet** [comment]
Hey, sure, why not?
What would you have in mind?

**Comment by yoannmoinet** [comment]
Closing this as no answers given for precisions.
