### ISSUE TITLE
Bundle size output?

### ISSUE THREAD

**Issue by slavafomin** [DataDog/build-plugin#43]
Hello!

Thank you for this great plugin!

However, I guess this should be an obvious feature, but I don't see the bundle size output in the log :)

Is it possible to enable it somehow?

Thanks!

**Comment by Ayc0** [comment]
👋 
What kind of metrics would you want?

1 for each generated asset? 1 for the total? both?

**Comment by yoannmoinet** [comment]
Closing for lack of answers.
