### ISSUE TITLE
Mark esbuild/webpack as optional peer deps

### ISSUE THREAD

**Issue by jakebailey** [DataDog/build-plugin#44]
### Is your feature request related to a problem? Please describe:

I noticed when installing this package into my project that it pulled in webpack. But, I only use esbuild.

### Describe the solution you'd like:

Rather than using just `peerDependencies`, also set `peerDependenciesMeta` in order to declare that these peer dependencies are optional. See: https://docs.npmjs.com/cli/v9/configuring-npm/package-json?v=true#peerdependenciesmeta

```json
"peerDependenciesMeta": {
    "esbuild": {
        "optional": true
    },
    "webpack": {
        "optional": true
    }
}
```

### Describe alternatives you've considered:

I'm not aware of any alternative to this, beside moving these deps to dev deps and assuming that the user will install the right thing. That might work too, but, not so much for types.

**Comment by Ayc0** [comment]
This should already be fixed by https://github.com/DataDog/build-plugin/pull/52
