### ISSUE TITLE
Compiler type doesn't match webpack Compiler type

### ISSUE THREAD

**Issue by igoldny** [DataDog/build-plugin#46]
### Describe what happened

Would like to include [build-plugin](https://github.com/DataDog/build-plugin) inside my internal webpack plugin.
I use webpack and am trying to pass webpack compiler into `BuildPlugin` but the types do not match.

### Steps to reproduce the issue:

Pass webpack compiler to `apply` will throw TS error:

```
import type { Compiler } from 'webpack';
new BuildPlugin().apply(compiler as Compiler);
```

### Expected behaviour:

```
import type { Compiler } from 'webpack';
new BuildPlugin().apply(compiler as Compiler);
```

### Actual behaviour:

```
import { Compiler as BuildPluginCompiler } from '@datadog/build-plugin/dist/types';      
new BuildPlugin().apply(compiler as unknown as BuildPluginCompiler);
```

**Comment by yoannmoinet** [comment]
I don't think this is relevant in v2 anymore.
Feel free to re-open if you reproduce the issue with v2.
